### ISSUE TITLE
Improvements on the structure of the project

### ISSUE THREAD

**Issue by algebraic-dev** [samueldurantes/fiapo#1]

**Comment by samueldurantes** [comment]
What is your proposal?

Do you pretend to improve handlers? Do you pretend to improve folder structure?

**Comment by algebraic-dev** [comment]
I want to improve the folder structure first to a structure that looks like:

- src
  -  Fiapo
     - Modules
       - User
         - Entities
           - Password.hs
           - User.hs
         - Controllers.hs (I think that we could split these controllers somehow but Idk how)
         - Routes.hs (Removes the routes from the App.hs)
         - Error.hs (It's made to improve the nested errors that you're making)
         - Repository.hs (The main problem with it is that it is coupled with mongodb)
     - Shared
       - Monad
         - Controller.hs (Monad for controllers and error handling inside controllers)
     - App.hs
     
It's not the best organization but It's better than using a Utils.hs and no transformers inside controllers that makes them dependent on the framework that we are using. The `Controllers.hs` is a little bit of a mess right now, It does not look right to me, we could split it inside a folder.

**Comment by samueldurantes** [comment]
> - Entities
>    - Password.hs
>    - User.hs

Why an entity for passwords?

> The main problem with it is that it is coupled with MongoDB

We can't escape this...

> The `Controllers.hs` is a little bit of a mess right now, It does not look right to me, we could split it inside a folder.

I agree, a controller for each action is ideal.

In general it's a good proposal, I just think we can simplify it by removing the entities and leaving all the "logic" inside the controllers.
